"""splent_feature_confirmemail

Revision ID: 126da35a357f
Revises:
Create Date: 2026-03-21 18:47:37.190083

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "126da35a357f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confirmemail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("confirmemail")
    # ### end Alembic commands ###
