"""splent_feature_confirmemail

Revision ID: 3d0c242c4406
Revises: 8c81c24a26d4
Create Date: 2026-03-21 23:56:23.642285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0c242c4406'
down_revision = '8c81c24a26d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
