"""splent_feature_confirmemail

Revision ID: 8c81c24a26d4
Revises: 981b848d2338
Create Date: 2026-03-21 23:53:12.957112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c81c24a26d4'
down_revision = '981b848d2338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
