"""splent_feature_confirmemail

Revision ID: 981b848d2338
Revises: 126da35a357f
Create Date: 2026-03-21 18:54:00.324230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981b848d2338'
down_revision = '126da35a357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
