"""splent_feature_confirmemail

Revision ID: af764089a442
Revises: 3d0c242c4406
Create Date: 2026-03-22 23:10:23.075982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af764089a442'
down_revision = '3d0c242c4406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
